### PR TITLE
Fix pointer lock UX

### PR DESCRIPTION
**Pull request by ajbura**

### CODE REVIEW

**Comment by robertlong** [comment]
Looking great so far! I do see one bug while the overlay is visible and you click the overlay background. I think the preferred behavior would be to close the overlay and enter pointer lock on the canvas.

https://user-images.githubusercontent.com/1753624/165992993-eb7449a5-9ac4-4a82-9b6f-4dacdfdb14ef.mov

**Comment by robertlong** [comment]
Also, I removed the button behavior from the "Open Overlay" / "Close Overlay" tip in the top left. We probably want to make that clickable again and make it toggle the overlay state.

**Comment by ajbura** [comment]
Fix overlay click as well as added the button.

**Comment by robertlong** [comment]
This is feeling 100x better! Great job @ajbura!

**Pull request merged**
