### PR TITLE
Chat timeline

### PR DESCRIPTION
**Pull request by ajbura**
image

This PR add chat timeline (Text message, Membership changes, Image) and ability to send message. Text messages doesn't have custom HTML support and Image message is not tested properly because of cross-origin policy.

### CODE REVIEW

**Comment by robertlong** [comment]
It's looking good but I noticed an issue when trying to load the chat view once you have loaded a room:

Screen Shot 2022-04-27 at 11 56 48 AM

```
Error: not dealing with load race here for now
    at hydrogen.es.js:13591:15
    at LogItem.run (hydrogen.es.js:3281:22)
    at ConsoleLogger._run (hydrogen.es.js:3402:25)
    at ConsoleLogger.run (hydrogen.es.js:3379:17)
    at ConsoleLogger.wrapOrRun (hydrogen.es.js:3363:19)
    at Room.openTimeline (hydrogen.es.js:13588:34)
    at TRRoomViewModel.load (useRoomViewModel.ts:122:39)
    at useRoomViewModel.ts:212:25
    at useAsync.ts:39:5
    at invokePassiveEffectCreate (react-dom.development.js:23487:20)
```

Could you fix that before we merge this?

**Comment by ajbura** [comment]
Yeah I looked at it. It happen when we have same room open as world (with chat open) and when we open it as chat it gives error that we already have Timeline open. I haven't fixed it because we will be filtering chat and world later and this senerio is not likely to happen.

Should I still fix it?

**Comment by ajbura** [comment]
I have fixed it for now. We are ready to merge 👍

**Comment by robertlong** [comment]
Cool, great work 👍

**Pull request merged**
