### PR TITLE
Chat overlay

### PR DESCRIPTION
**Pull request by ajbura**
image

### CODE REVIEW

**Comment by robertlong** [comment]
Looks good!

Two things I think we should change:

First is that the chat tabs in the bottom left should be visible regardless of what tab you have selected in the sidebar. So if I'm looking at worlds, I should be still be able to read incoming messages. This will get a little confusing with the `RoomPreview` component though. I think for now, rendering over the top of the `RoomPreview` will be fine.

The second is that the active/pressed state of the chat tabs should probably also be blue (although maybe a darker blue) not the grey color you have now. IMO it feels like the selection state isn't as responsive as a result.

Otherwise, looks great! Excited to see this with the timeline view embedded!

Adding `immer` sounds good to me. I've already been dealing with trying to maintain immutable maps in the `useObservableMap` hook, so that will be nice.

**Comment by ajbura** [comment]
image

You mean the roomTile need to be blue on selection (in World and Chats)? Currently it show it grey when selecting world but when opening chat it doesn't show it selected (it just add that to active chat in bottom right corner which shows what chat is visible).

About 1) This is little confusing. like: 
- user selected chat. (chat visible in overlay)
- user selected home tab. (chat still visible in overlay)
- user selected world. (chat replaced with world preview card)
Now i am unsure how to bring back chat overlay?
Selected world preview will always be there. one thing we can do is make chat visible again on selecting chat tab, but it's how it is currently. Maybe it is good as user can press ESC to get back to world view and if they open overlay again chat tab and chat overlay still be visible?

**Comment by robertlong** [comment]
We covered this feedback yesterday. I'm going to merge it now and we can fix in the next PR.

**Comment by ajbura** [comment]
I have already fixed the issue. Chat will be visible when you open world tab. Also fixed the selected state of roomtile

**Pull request merged**
