### PR TITLE
Editor Toolbar

### PR DESCRIPTION
**Pull request by ajbura**

### CODE REVIEW

**Comment by NateTheGreatt** [comment]
UI looks awesome, great work! found a small bug:

repro: open editor, focus editor, escape, open editor again
observation: tilde entered into script editor

**Comment by ajbura** [comment]
> repro: open editor, focus editor, escape, open editor again observation: tilde entered into script editor

I could not able to reproducing it.

**Comment by NateTheGreatt** [comment]
> > repro: open editor, focus editor, escape, open editor again observation: tilde entered into script editor
> 
> I could not able to reproducing it.

my bad, turns out there was a single tilde character in my world's saved script lol!

**Comment by robertlong** [comment]
Lets add a new mode `Inspect` which is on by default and has all of the editing features disabled in the top toolbar. We can move the `Scene` mode behind a feature flag. This will allow us to merge this PR and the awesome rework of the UI.

**Pull request merged**
