### PR TITLE
fly mode toggle

### LINKED ISSUE #99: Add toggleable fly mode
You should be able to press a key to toggle flying in a world. This will allow easier exploration of certain scenes with complex or troublesome collision or disconnected areas.

### PR DESCRIPTION
**Pull request by NateTheGreatt**
pressing `B` toggles fly mode

also fixes the falling animation playing when standing on the side of a crate

fixes #99

### CODE REVIEW

**Comment by robertlong** [comment]
Works great!

**Comment by ara4n** [comment]
i may be an idiot, but testing in chrome/macos on https://deploy-preview-337--thirdroom.netlify.app does nothing when i hit B

**Comment by NateTheGreatt** [comment]
> i may be an idiot, but testing in chrome/macos on https://deploy-preview-337--thirdroom.netlify.app/ does nothing when i hit B

did you try moving/flying around after B was pressed? working well on this side 🤔

**Comment by ara4n** [comment]
looks like i am an idiot.

needs B added to the keyboard shortcut modal tho

**Comment by NateTheGreatt** [comment]
> needs B added to the keyboard shortcut modal tho

good catch! added

**Comment by robertlong** [comment]
Awesome, nice work!

**Pull request merged**
