### PR TITLE
Add Bloom Postprocessing

### LINKED ISSUE #124: Postprocessing Effects
We should support the following postprocessing effects:
- [ ] Depth of Field
- [ ] Bloom
- [ ] Tonemapping

And it should work with MSAA via WebGL2's multisampled framebuffers.

### PR DESCRIPTION
**Pull request by robertlong**
Adds Three's UnrealBloomPass. I've excluded the depth of field for now as the perf cost is a little too high right now. Also I tried the SMAAPass but found that it produced significantly worse results so I reverted back to MSAA

Closes #124

### CODE REVIEW

**Review by NateTheGreatt — APPROVED** [review]
lgtm!

**Comment by ara4n** [comment]
(i think it's absolutely fine to skip DOF for now, tbh)

**Comment by robertlong** [comment]
Before we merge this I want to look into the SMAA pass further. It seems pretty broken.

**Review by NateTheGreatt — APPROVED** [review]
tested, looks great. mergin'

**Pull request merged**
